% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Apr-2021 01:22:46
%  MATLAB version: 9.9.0.1570001 (R2020b) Update 4
% -------------------------------------------------------------------
                                 

base_dir = ['/home/kelly/Insync/lab@sjulsonlab.org/Google Drive/lab-sha' ...
            'red/lab_projects/ectopic_mutant_GPCRs/4_Animal_Behavior/LA' ...
            'MuOR_Open_Field_Cohort01/LAMuOR_OF_Cohort01_3-16-2021/DLC_' ...
            'RESULTS/'];

color_theme = '#000000';

header2 = 15;

header3 = 15;

origin = ['/home/kelly/Insync/lab@sjulsonlab.org/Google Drive/lab-share' ...
          'd/lab_projects/LAMuOR-Gi/4_Animal_Behavior/Open_Field_Assay/' ...
          'LAMuOR_Open_Field_Cohort01'];

select_type = 1;

start_time = 9000;

stop_time = 50000;

